package catering.businesslogic.summaryform;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

import catering.businesslogic.event.Event;
import catering.businesslogic.staff.Role;
import catering.businesslogic.user.User;
import catering.persistence.PersistenceManager;

/**
 * The SummaryForm class represents a summary sheet entity ("scheda riepilogativa").
 * It is created by an organizer for a specific event and can contain details
 * about associated events and required roles.
 */
public class SummaryForm {

    private int id; // The unique identifier for the summary form, generated by the database.
    private String description;
    private boolean inUse;
    private final User owner;

    // These lists are managed in-memory and are not directly persisted in the SummaryForms table.
    private final List<Event> associatedEvents;
    private final List<Role> associatedRoles;

    /**
     * Private constructor to enforce object creation via the factory method.
     * @param owner The user who owns this form.
     * @param description A textual description of the form.
     */
    private SummaryForm(User owner, String description) {
        this.id = 0; // A new, unsaved summary form has an ID of 0
        this.owner = owner;
        this.description = description;
        this.inUse = false;
        this.associatedEvents = new ArrayList<>();
        this.associatedRoles = new ArrayList<>();
    }

    /**
     * Factory method to create a new SummaryForm.
     * @param owner The user creating the form.
     * @param description The description for the form.
     * @return A new instance of SummaryForm.
     */
    public static SummaryForm create(User owner, String description) {
        return new SummaryForm(owner, description);
    }
    
    // Getters and Setters

    public int getId() { 
        return id; 
    }

    public boolean isOwner(User user) {
        return this.owner != null && this.owner.equals(user);
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public boolean isInUse() {
        return inUse;
    }

    public void setInUse(boolean inUse) {
        this.inUse = inUse;
    }

    public List<Event> getAssociatedEvents() {
        return associatedEvents;
    }

    public List<Role> getAssociatedRoles() {
        return associatedRoles;
    }

    public User getOwner() {
        return owner;
    }

    // List Management

    public boolean containsEvent(Event ev) {
        return associatedEvents.contains(ev);
    }

    public boolean containsRole(Role r) {
        return associatedRoles.contains(r);
    }

    public void addEvent(Event ev) {
        if (ev != null && !associatedEvents.contains(ev)) {
            associatedEvents.add(ev);
        }
    }

    public void addRole(Role r) {
        if (r != null && !associatedRoles.contains(r)) {
            associatedRoles.add(r);
        }
    }

    // Persistence Methods

    /**
     * Saves a new SummaryForm to the database.
     * @return true if the operation was successful, false otherwise.
     */
    public boolean save() {
        if (this.id != 0) return false;
        String query = "INSERT INTO SummaryForms (description, in_use, owner_id) VALUES (?, ?, ?)";
        int inUseInt = this.inUse ? 1 : 0;
        int rows = PersistenceManager.executeUpdate(query, this.description, inUseInt, this.owner.getId());
        if (rows > 0) {
            this.id = PersistenceManager.getLastId();
            return true;
        }
        return false;
    }

    /**
     * Updates an existing SummaryForm in the database.
     * @return true if the operation was successful, false otherwise.
     */
    public boolean update() {
        if (this.id == 0) return false;
        String query = "UPDATE SummaryForms SET description = ?, in_use = ? WHERE id = ?";
        int inUseInt = this.inUse ? 1 : 0;
        int rows = PersistenceManager.executeUpdate(query, this.description, inUseInt, this.id);
        return rows > 0;
    }

    /**
     * Deletes this SummaryForm from the database.
     * @return true if the operation was successful, false otherwise.
     */
    public boolean delete() {
        if (this.id == 0) return false;
        String query = "DELETE FROM SummaryForms WHERE id = ?";
        int rows = PersistenceManager.executeUpdate(query, this.id);
        return rows > 0;
    }

    /**
     * Loads a SummaryForm from the database by its ID.
     * @param formId The ID of the form to load.
     * @return The loaded SummaryForm, or null if not found.
     */
    public static SummaryForm load(int formId) {
        final SummaryForm[] result = new SummaryForm[1];
        String query = "SELECT * FROM SummaryForms WHERE id = ?";
        PersistenceManager.executeQuery(query, rs -> {
            result[0] = fromResultSet(rs);
        }, formId);
        return result[0];
    }
    
    /**
     * Private helper method to create a SummaryForm instance from a database row.
     * This method is responsible for mapping the ResultSet columns to the object's fields.
     * @param rs The ResultSet positioned on the correct row to be mapped.
     * @return A new, populated SummaryForm object.
     * @throws SQLException if a database access error occurs or this method is called on a closed result set.
     */
    private static SummaryForm fromResultSet(ResultSet rs) throws SQLException {
        int ownerId = rs.getInt("owner_id");
        User owner = User.load(ownerId);
        SummaryForm sf = new SummaryForm(owner, rs.getString("description"));
        sf.id = rs.getInt("id");
        sf.inUse = rs.getBoolean("in_use");
        return sf;
    }
}