package catering.businesslogic.staff;

import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Objects;


import catering.persistence.PersistenceManager;
import catering.persistence.ResultHandler;

/**
 * The Role class represents a specific role or task within an event.
 * It can be assigned to a Staff member and has its own persistence logic.
 */
public class Role {

    private int id; // The unique identifier for the role, generated by the database.
    private Staff worker; // The Staff member assigned to this role. Null if the role is unassigned.
    private String name; // The name of the role (e.g., "Sommelier", "Head Waiter").
    private String description; // A description of the tasks and responsibilities of the role.
    private Date date; // The date associated with this role, typically the date of the event/service.
    private boolean isAssigned; // A flag indicating whether the role is currently assigned to a worker.

    /**
     * Private constructor to enforce object creation through the factory method.
     * Initializes a new role with a default ID of 0.
     */
    private Role() {
        this.id = 0; // A new role has no ID until it is saved.
    }

    /**
     * Factory method to create a new, unassigned role.
     * @param name The name of the role.
     * @param description A description of the role.
     * @param date The date for which the role is needed.
     * @return A new Role instance.
     */
    public static Role create(String name, String description, Date date) {
        Role role = new Role();
        role.name = name;
        role.description = description;
        role.date = date;
        role.isAssigned = false; // A new role isn't assigned by default.
        role.worker = null;
        return role;
    }

    // Getters and Setters

    public int getId() { 
        return id; 
    }

    public Staff getStaff() {
        return worker;
    }

    public String getName() {
        return name;
    }

    public String getDescription() {
        return description;
    }

    public Date getDate() {
        return date;
    }

    public boolean isAssigned() {
        return isAssigned;
    }

    /**
     * Assigns a worker to this role.
     * Also updates the 'isAssigned' status based on whether the worker is null.
     * @param worker The staff member to assign, or null to unassign.
     */
    public void setWorker(Staff worker) {
        this.worker = worker;
        this.isAssigned = (worker != null);
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public void setAssigned(boolean assigned) {
        this.isAssigned = assigned;
    }

    /**
     * Saves a new role to the database.
     * This method is static and takes the Role object to save as a parameter.
     * It sets the ID on the object after a successful insert.
     * @param roleToSave The Role object to persist.
     * @throws SQLException if a database access error occurs.
     */
    public static void create(Role roleToSave) throws SQLException {
        if (roleToSave.id != 0) return;

        String insertQuery = "INSERT INTO EventRoles (name, description, date, is_assigned, staff_id) VALUES (?, ?, ?, ?, ?)";
        Integer staffId = (roleToSave.worker != null) ? roleToSave.worker.getSerialNumber() : null;

        int rows = PersistenceManager.executeUpdate(insertQuery,
                roleToSave.name,
                roleToSave.description,
                roleToSave.date,
                roleToSave.isAssigned,
                staffId
        );

        if (rows > 0) {
            roleToSave.id = PersistenceManager.getLastId();
        }
    }

    /**
     * Updates the current role's data in the database.
     * @return true if the update was successful, false otherwise.
     */
    public boolean update() {
        if (this.id == 0) return false; // Not saved yet
        String query = "UPDATE EventRoles SET name = ?, description = ?, date = ?, is_assigned = ?, staff_id = ? WHERE id = ?";
        Integer staffId = (worker != null) ? worker.getSerialNumber() : null;
        int rows = PersistenceManager.executeUpdate(query, this.name, this.description, this.date, this.isAssigned, staffId, this.id);
        return rows > 0;
    }

    /**
     * Deletes the current role from the database.
     * @return true if the deletion was successful, false otherwise.
     * @throws RoleException if the role is currently assigned and cannot be deleted.
     */
    public boolean delete() throws RoleException {
        if (this.id == 0) return false;
        if (this.isAssigned()) {
            throw new RoleException("The role you are trying to delete is in use.");
        }
        String query = "DELETE FROM EventRoles WHERE id = ?";
        int rows = PersistenceManager.executeUpdate(query, this.id);
        return rows > 0;
    }

    /**
     * Loads a single role from the database by its ID.
     * @param name The name of the role to load.
     * @return The loaded Role object, or null if not found.
     */
    public static Role loadRole(String name) {
        final Role[] resultHolder = new Role[1];
        String query = "SELECT * FROM EventRoles WHERE name = ?";

        PersistenceManager.executeQuery(query, new ResultHandler() {
            @Override
            public void handle(ResultSet rs) throws SQLException {
                resultHolder[0] = fromResultSet(rs);
            }
        }, name);
        return resultHolder[0];
    }

    /**
     * Private helper method to create a Role instance from a database row.
     * @param rs The ResultSet positioned on the correct row.
     * @return A populated Role object.
     * @throws SQLException if a database access error occurs.
     */
    private static Role fromResultSet(ResultSet rs) throws SQLException {
        Role r = new Role();
        r.id = rs.getInt("id");
        r.name = rs.getString("name");
        r.description = rs.getString("description");
        r.date = rs.getDate("date");
        r.isAssigned = rs.getBoolean("is_assigned");
        int staffId = rs.getInt("staff_id");
        if (!rs.wasNull()) {
            r.worker = Staff.loadStaff(staffId);
        }
        return r;
    }

    // Object Overrides

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Role role = (Role) o;
        return id == role.id && id != 0;
    }

    @Override
    public int hashCode() {
        return Objects.hash(id);
    }
    
    @Override
    public String toString() {
        return "Role{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", isAssigned=" + isAssigned +
                ", worker=" + (worker != null ? worker.getSerialNumber() : "none") +
                '}';
    }
}